version: '3.9'
networks:
    bridge_net:
        driver: bridge
services:
    postgres:
        container_name: pg_database
        image: postgres:latest
        env_file:
            - config.env
        ports:
            - "5432:5432"
        networks:
            - bridge_net
        volumes:
            - ./docker/volumes/postgres/data:/var/lib/postgresql/data
        user: 1000:1000
    node-cli:
        container_name: node_cli
        build:
            context: docker/images/node
        volumes:
            - ./public:/app
            - ./config.env:/app/.env
        networks:
            - bridge_net
